# Generated by Django 3.2.12 on 2022-04-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import findingJob.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findingJob', '0018_jobcategory_category_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='category_logo',
            field=models.ImageField(blank=True, default='defaultlogo.png', null=True, upload_to='category_logo', validators=[findingJob.validators.validate_file_extension]),
        ),
    ]
